version: "3.8"

services:
  web:
    container_name: txrnup
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
        - "5435:5435"
    volumes:
      - postgres-db-7:/var/lib/postgresql/data

volumes:
  postgres-db-7: